// Generated by rstantools.  Do not edit by hand.

/*
    greencrab.toolkit is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    greencrab.toolkit is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with greencrab.toolkit.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.26.1-4-gd72b68b7-dirty
#include <stan/model/model_header.hpp>
namespace model_greencrabtools_traptypes_namespace {
inline void validate_positive_index(const char* var_name, const char* expr,
                                    int val) {
  if (val < 1) {
    std::stringstream msg;
    msg << "Found dimension size less than one in simplex declaration"
        << "; variable=" << var_name << "; dimension size expression=" << expr
        << "; expression value=" << val;
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
inline void validate_unit_vector_index(const char* var_name, const char* expr,
                                       int val) {
  if (val <= 1) {
    std::stringstream msg;
    if (val == 1) {
      msg << "Found dimension size one in unit vector declaration."
          << " One-dimensional unit vector is discrete"
          << " but the target distribution must be continuous."
          << " variable=" << var_name << "; dimension size expression=" << expr;
    } else {
      msg << "Found dimension size less than one in unit vector declaration"
          << "; variable=" << var_name << "; dimension size expression=" << expr
          << "; expression value=" << val;
    }
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using std::pow;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using stan::model::cons_list;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::nil_index_list;
using namespace stan::math;
using stan::math::pow; 
stan::math::profile_map profiles__;
static int current_statement__= 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in 'greencrabtools_traptypes', line 12, column 4 to column 16)",
                                                      " (in 'greencrabtools_traptypes', line 24, column 2 to column 10)",
                                                      " (in 'greencrabtools_traptypes', line 25, column 2 to column 19)",
                                                      " (in 'greencrabtools_traptypes', line 18, column 6 to column 85)",
                                                      " (in 'greencrabtools_traptypes', line 17, column 17 to line 19, column 5)",
                                                      " (in 'greencrabtools_traptypes', line 17, column 4 to line 19, column 5)",
                                                      " (in 'greencrabtools_traptypes', line 21, column 2 to column 49)",
                                                      " (in 'greencrabtools_traptypes', line 2, column 4 to column 19)",
                                                      " (in 'greencrabtools_traptypes', line 3, column 10 to column 11)",
                                                      " (in 'greencrabtools_traptypes', line 3, column 4 to column 28)",
                                                      " (in 'greencrabtools_traptypes', line 4, column 4 to column 22)",
                                                      " (in 'greencrabtools_traptypes', line 5, column 4 to column 30)",
                                                      " (in 'greencrabtools_traptypes', line 6, column 10 to column 11)",
                                                      " (in 'greencrabtools_traptypes', line 6, column 4 to column 33)",
                                                      " (in 'greencrabtools_traptypes', line 7, column 10 to column 11)",
                                                      " (in 'greencrabtools_traptypes', line 7, column 4 to column 33)",
                                                      " (in 'greencrabtools_traptypes', line 8, column 4 to column 31)",
                                                      " (in 'greencrabtools_traptypes', line 9, column 4 to column 31)"};
#include <stan_meta_header.hpp>
class model_greencrabtools_traptypes final : public model_base_crtp<model_greencrabtools_traptypes> {
private:
  int C;
  std::vector<int> E;
  double phi;
  std::vector<double> logmupriors;
  std::vector<int> minnow;
  std::vector<int> shrimp;
  double beta1;
  double beta2;
 
public:
  ~model_greencrabtools_traptypes() { }
  
  inline std::string model_name() const final { return "model_greencrabtools_traptypes"; }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.26.1-4-gd72b68b7-dirty", "stancflags = "};
  }
  
  
  model_greencrabtools_traptypes(stan::io::var_context& context__,
                                 unsigned int random_seed__ = 0,
                                 std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static const char* function__ = "model_greencrabtools_traptypes_namespace::model_greencrabtools_traptypes";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 8;
      context__.validate_dims("data initialization","C","int",
          context__.to_vec());
      C = std::numeric_limits<int>::min();
      
      current_statement__ = 8;
      C = context__.vals_i("C")[(1 - 1)];
      current_statement__ = 8;
      current_statement__ = 8;
      check_greater_or_equal(function__, "C", C, 1);
      current_statement__ = 9;
      validate_non_negative_index("E", "C", C);
      current_statement__ = 10;
      context__.validate_dims("data initialization","E","int",
          context__.to_vec(C));
      E = std::vector<int>(C, std::numeric_limits<int>::min());
      
      current_statement__ = 10;
      assign(E, nil_index_list(), context__.vals_i("E"),
        "assigning variable E");
      current_statement__ = 10;
      for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
        current_statement__ = 10;
        current_statement__ = 10;
        check_greater_or_equal(function__, "E[sym1__]", E[(sym1__ - 1)], 0);}
      current_statement__ = 11;
      context__.validate_dims("data initialization","phi","double",
          context__.to_vec());
      phi = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 11;
      phi = context__.vals_r("phi")[(1 - 1)];
      current_statement__ = 11;
      current_statement__ = 11;
      check_greater_or_equal(function__, "phi", phi, 0);
      current_statement__ = 12;
      context__.validate_dims("data initialization","logmupriors","double",
          context__.to_vec(2));
      logmupriors = std::vector<double>(2, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 12;
      assign(logmupriors, nil_index_list(), context__.vals_r("logmupriors"),
        "assigning variable logmupriors");
      current_statement__ = 13;
      validate_non_negative_index("minnow", "C", C);
      current_statement__ = 14;
      context__.validate_dims("data initialization","minnow","int",
          context__.to_vec(C));
      minnow = std::vector<int>(C, std::numeric_limits<int>::min());
      
      current_statement__ = 14;
      assign(minnow, nil_index_list(), context__.vals_i("minnow"),
        "assigning variable minnow");
      current_statement__ = 14;
      for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
        current_statement__ = 14;
        current_statement__ = 14;
        check_greater_or_equal(function__, "minnow[sym1__]",
                               minnow[(sym1__ - 1)], 0);}
      current_statement__ = 15;
      validate_non_negative_index("shrimp", "C", C);
      current_statement__ = 16;
      context__.validate_dims("data initialization","shrimp","int",
          context__.to_vec(C));
      shrimp = std::vector<int>(C, std::numeric_limits<int>::min());
      
      current_statement__ = 16;
      assign(shrimp, nil_index_list(), context__.vals_i("shrimp"),
        "assigning variable shrimp");
      current_statement__ = 16;
      for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
        current_statement__ = 16;
        current_statement__ = 16;
        check_greater_or_equal(function__, "shrimp[sym1__]",
                               shrimp[(sym1__ - 1)], 0);}
      current_statement__ = 17;
      context__.validate_dims("data initialization","beta1","double",
          context__.to_vec());
      beta1 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 17;
      beta1 = context__.vals_r("beta1")[(1 - 1)];
      current_statement__ = 17;
      current_statement__ = 17;
      check_greater_or_equal(function__, "beta1", beta1, -0.99999);
      current_statement__ = 18;
      context__.validate_dims("data initialization","beta2","double",
          context__.to_vec());
      beta2 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 18;
      beta2 = context__.vals_r("beta2")[(1 - 1)];
      current_statement__ = 18;
      current_statement__ = 18;
      check_greater_or_equal(function__, "beta2", beta2, -0.99999);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 0U;
    
    try {
      num_params_r__ += 1;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI, stan::require_vector_like_t<VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char* function__ = "model_greencrabtools_traptypes_namespace::log_prob";
(void) function__;  // suppress unused var warning
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      local_scalar_t__ log_mu;
      log_mu = DUMMY_VAR__;
      
      current_statement__ = 1;
      log_mu = in__.scalar();
      {
        current_statement__ = 6;
        for (int j = 1; j <= C; ++j) {
          current_statement__ = 4;
          lp_accum__.add(
            neg_binomial_2_lpmf<propto__>(E[(j - 1)],
              (((1 + (beta1 * shrimp[(j - 1)])) + (beta2 * minnow[(j - 1)]))
                * stan::math::exp(log_mu)), phi));}
        current_statement__ = 7;
        lp_accum__.add(
          normal_lpdf<propto__>(log_mu, logmupriors[(1 - 1)],
            logmupriors[(2 - 1)]));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr>
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    static const char* function__ = "model_greencrabtools_traptypes_namespace::write_array";
(void) function__;  // suppress unused var warning
    (void) function__;  // suppress unused var warning
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      double log_mu;
      log_mu = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      log_mu = in__.scalar();
      vars__.emplace_back(log_mu);
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      double mu;
      mu = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      mu = stan::math::exp(log_mu);
      vars__.emplace_back(mu);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, stan::require_std_vector_t<VecVar>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void transform_inits_impl(const stan::io::var_context& context__,
                                   VecI& params_i__, VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      double log_mu;
      log_mu = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      log_mu = context__.vals_r("log_mu")[(1 - 1)];
      vars__.emplace_back(log_mu);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__.clear();
    names__.emplace_back("log_mu");
    names__.emplace_back("mu");
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    dimss__.clear();
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "log_mu");
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "mu");
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "log_mu");
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "mu");
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"log_mu\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"log_mu\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      std::vector<double> vars_vec(vars.size());
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i) {
        vars.coeffRef(i) = vars_vec[i];
      }
    }
    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }
    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
  
    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits_impl(context, params_i, params_r_vec, pstream);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i) {
        params_r.coeffRef(i) = params_r_vec[i];
      }
    }
    inline void transform_inits(const stan::io::var_context& context,
                                std::vector<int>& params_i,
                                std::vector<double>& vars,
                                std::ostream* pstream = nullptr) const final {
      transform_inits_impl(context, params_i, vars, pstream);
    }        
};
}
using stan_model = model_greencrabtools_traptypes_namespace::model_greencrabtools_traptypes;
#ifndef USING_R
// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_greencrabtools_traptypes_namespace::profiles__;
}
#endif
#endif
